set(VCPKG_TARGET_ARCHITECTURE x64)

if(${PORT} MATCHES "glad")
	message(STATUS "> ${PORT} will be built as static...")
	set(VCPKG_CRT_LINKAGE static)
	set(VCPKG_LIBRARY_LINKAGE static)
else()
	message(STATUS "> ${PORT} will be built as dynamic...")
	set(VCPKG_CRT_LINKAGE dynamic)
	set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()

if(${PORT} MATCHES "glm")
	message(STATUS "> ${PORT} will be built as static...")
	set(VCPKG_CRT_LINKAGE static)
	set(VCPKG_LIBRARY_LINKAGE static)
else()
	message(STATUS "> ${PORT} will be built as dynamic...")
	set(VCPKG_CRT_LINKAGE dynamic)
	set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()

if(${PORT} MATCHES "vulkan")
	message(STATUS "> ${PORT} will be built as static...")
    
	set(VCPKG_CRT_LINKAGE static)
	set(VCPKG_LIBRARY_LINKAGE static)
else()
	message(STATUS "> ${PORT} will be built as dynamic...")
	set(VCPKG_CRT_LINKAGE dynamic)
	set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()